version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles   # Change to PST timezone
      - WEBUI_PORT=8090
    volumes:
      - /home/brian/home-infra/configs/qbittorrent:/config
      - /mnt/media:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    network_mode: host

