version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
    network_mode: host
    restart: always
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    ports:
      - "8080:8080"
    devices:
      - "/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD48E8C-if00:/dev/ttyACM0"
    volumes:
      - "/home/brian/home-infra/configs/zigbee2mqtt/data:/app/data"
      - "/run/udev:/run/udev:ro"
    network_mode: host
    restart: always
    depends_on:
      - mosquitto
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/brian/home-infra/configs/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

